server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

spring:
  servlet:
    multipart:
      max-file-size: 40MB
      max-request-size: 400MB
  liquibase:
    change-log: classpath:migrations/db.changelog-master.yaml
  application:
    name: cloud-service
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:sa}
    password: ${POSTGRES_PASSWORD:password}
s3:
  url: ${MINIO_URL:http://localhost:9000}
  accessKey: ${MINIO_ACCESS_KEY:minioadmin}
  secretKey: ${MINIO_SECRET_KEY:minioadmin}

properties:
  page-size: 20

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} | %-5level | %logger | %m %X%n"

jwt:
  ttl-in-min: ${TOKEN_TTL:10}
  secret-key: ${TOKEN_SECRET}
