spring:
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 60MB
  liquibase:
    change-log: classpath:migrations/db.changelog-master.yaml
  application:
    name: cloud-service
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:sa}
    password: ${POSTGRES_PASSWORD:password}
s3:
  url: ${MINIO_URL}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}

properties:
  page-size: 20

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} | %-5level | %logger | %m %X%n"
